### ISSUE TITLE
Реализовать api метод для Осуществления платежа по кредиту

### ISSUE THREAD

**Issue by BarracudaPff** [apmath-web/credit-kotlin#14]
- Создать Action
- Добавить в Handler
- Решить проблему с immutable VO-Payment
- Сделать regular платежи
- Определиться со сроками regular
- добавить monthsDiff
- обработать платеж через 1е января
- Сделать early платежи
- Сделать перерасчет кредита
- Добавить новые exceptions при необходимости
- Дописать фильтрованный вывод платежей

**Comment by malinink** [comment]
Для реализации бизнес логики погашения платежа - заведите отдельную задачу с более детальным описанием и ddd меткой. (если еще не завели)
