### ISSUE TITLE
Реализовать api метод для Вывода платежей по кредиту

### ISSUE THREAD

**Issue by BarracudaPff** [apmath-web/credit-kotlin#15]
- Создать Action
- Добавить в Handler
- Реализовать тип regular
- Реализовать тип early
- Реализовать тип next
- Реализовать состояние paid
- Реализовать состояние upcoming
- Реализовать комбинацию типов и состояний
- Дополнить Issue при необходимости

**Comment by malinink** [comment]
Добавьте еще информацию про viewModel очевидно все эти типы нам необходимы для того чтобы viewModel платежа можно было реализовать.
