### ISSUE TITLE
Добавить обработку ошибок в Handler

### ISSUE THREAD

**Issue by BarracudaPff** [apmath-web/credit-kotlin#6]
- Добавить обработку ошибок в `Handler`
- Создать иерархию ошибок

**Comment by malinink** [comment]
2 и 3 сделано и это не модели ;)
Вы точно хотите этой задачей заняться?

**Comment by BarracudaPff** [comment]
Вы же сами говорили что нужно добавить большой `try-cacth` в `Handler`. Про `Validation` и `Message ` не заметил)
А на вопрос - да, хочу

**Comment by malinink** [comment]
Опишите тогда сначала тут, какие классы ошибок сделаете, как каждую из них будете обрабатывать (в этой же задаче вам необходимо правильно возвращать ответ, при получении ошибки, т.е. соответствовать спецификации).

**Comment by malinink** [comment]
@BarracudaPff от вас требуется проанализировать #8 
см. `// TODO` которые я оставил в коде, и написать в задаче максимально полно как и что необходимо сделать.
Сразу скажу, на мой взгляд задача сложная, и лучше бы вы для начала api сделали, но эта задача блокирующая и сделать её необходимо до api. 

Посему, если у вас не будет идей до чт вечера, я задачу поставлю на себя и сделаю сам.

**Comment by BarracudaPff** [comment]
Оокей, можно сделать так:
- `ResponceException`
  - `BadRequestException`
  - `NotFoundException`
  - `CreditStoreIdException`
  - `CreditRemoveIdException`
  - `CreditAbsentIdException`
  - `CreditUnidentifiedIdException`
  - `AlreadyPaidException`

Тогда в ошибках можно делаем метод `responce()` который будет возвращать `FullHttpResponse`
И в методе `Handler.handle` прописать
```kotlin
return try {
    routeRequest(request)
} catch (e: ResponceException) {
    e.response
}
```
Если ошибка требует специфической обработки, то добавляем еще `catch`
Так будет выглядеть лаконично и без огромного `try-catch`
###
P.S.
Еще можно `Validation` вернуть как ошибку

**Comment by BarracudaPff** [comment]
Можно еще разбить ошибки, но какой-то выгоды пока не вижу
- `ResponceException`
  - `ApiException`
    - `BadRequestException`
    - `NotFoundException`
  - `CreditIdException`
    - `StoreIdException`
    - `RemoveIdException`
      - `AbsentIdException`
       - `UnidentifiedIdException`
  - `PaymentException`
    - `AlreadyPaidException`

**Comment by malinink** [comment]
Немного не то, итак я разделил все ошибки на 2 больших категории, domain и общие, domain - это все исключения, выбрасываемые из доменных сущностей.
Предлагаю их наследовать от:
 - Exception, если ошибку необходимо перехватывать
 - RuntimeException, если ошибка произошла по вине разработчика (сейчас все ошибки которые есть в domain/exceptions - необходимо перевести в базу от RE).
Соответственно необходимо понять какие теоретически ещё могут быть ошибки в domain, и понять какое поведение они должны моделировать. Например сейчас я вижу только 2 типа, это ошибки приводящие к ответу 400 и 404. Возможно я ошибаюсь и будут еще другие.

Соответственно в exceptions базовых - должны быть уже те оибки по которым handler сможет отдать необходимый ответ. т.е. сформировать тело 404 ошибки, 400 и добавить в это тело всю необходимую инфомрацию, поэтому необходимо продумать реализацию этих ошибок.

Ну а потом уже написать перехватчик, который все базовые ошибки будет перехватывать и возвращать корректный ответ.

Ну а в конкретных экшенах мы уже будем перехватывать доменные ошибки и формировать базовые из них. Или просто генерировать базовые (например из validation)

Теперь предлагаю еще раз обсудить конкретику.

**Comment by BarracudaPff** [comment]
А зачем сейчас продумывать Runtime ошибки? Не легче будет создать для них базу и наследовать при необходимости в добавлении новой ошибки?

**Comment by BarracudaPff** [comment]
С реализацией понял, давайте тогда сделаю пример на какой-нибудь BadRequest ошибке и скину сюда
